### ISSUE TITLE
trusted web app

### ISSUE THREAD

**Issue by kindOfCurly** [UniRegensburg/unsere-app-fur-die-universitat-regensburg-ur-fit#119]
Our app should be a trusted web app.
For we miss many information this is only possible as a beta-version.

**Comment by Naarij** [comment]
Looks like we need a performance score of 80+ and a PWA score of 100 to turn a pwa into a twa.
I'm checking on that but as we stand for now we are missing the maesked symbol for 100% pwa (see #114 ). I'll quicky fix this and then work on this issue

**Comment by kindOfCurly** [comment]
If the app is a twa please add info about that in the readme.
And also add some info [here](https://github.com/UniRegensburg/unsere-app-fur-die-universitat-regensburg-ur-fit/wiki/notes-on-continuing-the-work#potentielle-probleme-und-ihre-l%C3%B6sungen) about beta and not beta and what has to be done in future...
