### ISSUE TITLE
implement database models

### ISSUE THREAD

**Issue by Naarij** [UniRegensburg/unsere-app-fur-die-universitat-regensburg-ur-fit#5]
To have database consistency in the code, most database tables and relations should be represented as simple objects inside the code. Once they are implemented, they can be used inside the code to exchange data with the database with the help of utility methods, see #4 . For the first steps a simple translation of the database model to js objects needs to be done.

**Comment by kindOfCurly** [comment]
This is the data model we developed together (18-02-2021):

[Datenmodell.pdf](https://github.com/UniRegensburg/unsere-app-fur-die-universitat-regensburg-ur-fit/files/6002400/Datenmodell.pdf)
