### ISSUE TITLE
Add flexibel api server for simple tasks

### ISSUE THREAD

**Issue by cetceeve** [UniRegensburg/unsere-app-fur-die-universitat-regensburg-ur-fit#67]
Main tasks:
- proxying of authentication and mensa requests
- CSRF (cross site request forgery) protection for authentication
- (future) Telemetry/ Logging

**Comment by cetceeve** [comment]
Packages to be user:
- [expressjs](http://expressjs.com/)
- [expressjs proxy middleware](https://www.npmjs.com/package/http-proxy-middleware)
- [expressjs csrf protection middleware](http://expressjs.com/en/resources/middleware/csurf.html)

**Comment by kindOfCurly** [comment]
closed by #69
