### ISSUE TITLE
refact login screen for usability

### ISSUE THREAD

**Issue by kindOfCurly** [UniRegensburg/unsere-app-fur-die-universitat-regensburg-ur-fit#71]
- homescreen should be ProtectedRoute
- add a short hint (info button or subtitle) to the login screen to explain the purpose of the app (= what is my benefit if I log in)
- add a hint 'abc12345' for the input field
- change wording: 'NDS-Account' to 'RZ-Account'
- login screen should contain UR-logo

**Comment by cetceeve** [comment]
Additionally:
- inform user if the system is working
- inform user about wrong credentials
- informs user about if authentication system is unavailable
