### ISSUE TITLE
refact ProtectedRoute

### ISSUE THREAD

**Issue by kindOfCurly** [UniRegensburg/unsere-app-fur-die-universitat-regensburg-ur-fit#73]
If the app is accessed via link other than '/' the ProtectedRoute should redirect to that link (instead of always redirecting to home screen).

**Comment by cetceeve** [comment]
The redirect is actually happening in the Loginscreen.
From my perspective the Protected Route is fine.

I will check this today.

**Comment by kindOfCurly** [comment]
Good point!
So maybe this issue is more linked to #71 ?
